FastDB: dbReference< T > Class Template Reference
dbReference< T > Class Template Reference
#include <reference.h>