FastDB: dbTimeSeriesReverseIterator< T > Class Template Reference
dbTimeSeriesReverseIterator< T > Class Template Reference
#include <timeseries.h>
Public Member Functions
void start (dbTimeSeriesProcessor< T > *processor, oid_t oid, time_t from, time_t till)
bool current (T &elem)
bool next ()
void reset ()
dbTimeSeriesReverseIterator ()
Detailed Description
template<class T>
class dbTimeSeriesReverseIterator< T >
Time series reverse iterator
Constructor & Destructor Documentation
template<class T > dbTimeSeriesReverseIterator< T >::dbTimeSeriesReverseIterator () [inline]
Iterator costructor. If current() or next() method will always return false if them are invoked prior to start()
Member Function Documentation
template<class T > bool dbTimeSeriesReverseIterator< T >::current (T & elem) [inline]
Get current iterator element
Returns:
true if there is current element, false otherwise
template<class T > bool dbTimeSeriesReverseIterator< T >::next () [inline]
Move iterator position to next element.
Returns:
true if next element exists, false otherwise
References dbCursor< T >::prev().
template<class T > void dbTimeSeriesReverseIterator< T >::reset () [inline]
Reset iterator to the initial state
References dbCursor< T >::last().
template<class T > void dbTimeSeriesReverseIterator< T >::start (dbTimeSeriesProcessor< T > * processor, oid_t oid, time_t from, time_t till) [inline]
Start iteration through elements belonging to the specified range.
Parameters:
processor pointer to time series processor
oid time series identifer (OID of the object associated with this time series)
from inclusive low bound for element timestamp (set 0 to disable this criteria)
till inclusive high bound for element timestamp (set INFINITE_TIME to disable this criteria)
References dbTimeSeriesProcessor< T >::_openIteratorCursor(), dbCursor< T >::get(), dbCursor< T >::last(), and dbCursor< T >::prev().
The documentation for this class was generated from the following file:
timeseries.h